parameters:
  rules:
    array_syntax:
      syntax: short
    declare_equal_normalize: true
    declare_strict_types: false
    blank_lines_before_namespace: false
    fully_qualified_strict_types:
        leading_backslash_in_global_namespace: false
        phpdoc_tags: []
